# Generated by Django 2.2 on 2020-11-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist_name',
            new_name='item_name',
        ),
    ]
